=== fivegg/bbonita-console-5-10-1/forms/forms-migration/src/test/resources/forms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Application forms definition schema for Bonita open solution.
			Copyright (C) 2009, 2010 BonitaSoft S.A.
    	</xsd:documentation>
	</xsd:annotation>

	<xsd:element name="forms-definition" type="FormsDefinition" />

	<xsd:complexType name="FormsDefinition">
		<xsd:sequence>
			<xsd:element name="welcome-page" type="xsd:string" minOccurs="0" />
			<xsd:element name="external-welcome-page" type="xsd:string" minOccurs="0" />
			<xsd:element name="home-page" type="xsd:string" minOccurs="0" />
			<xsd:element name="migration-product-version" type="xsd:string" minOccurs="0" />
			<xsd:element name="application" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="application-label" type="xsd:string" />
						<xsd:element name="application-layout" type="xsd:string" minOccurs="0" />
						<xsd:element name="mandatory-symbol" type="xsd:string" minOccurs="0" />
						<xsd:element name="mandatory-label" type="xsd:string" minOccurs="0" />
						<xsd:element name="mandatory-style" type="xsd:string" minOccurs="0" />
						<xsd:element name="error-template" type="xsd:string" minOccurs="0" />
						<xsd:element name="forms" type="Forms" minOccurs="0" />
						<xsd:element name="permissions" type="xsd:string" />
					</xsd:all>
					<xsd:attribute name="name" type="xsd:string" use="required" />
					<xsd:attribute name="version" type="xsd:string" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="product-version" type="xsd:string" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Forms">
		<xsd:sequence>
			<xsd:element name="form" type="Form" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Form">
		<xsd:all>
			<xsd:element name="pages" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="page" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:all>
									<xsd:element name="page-label" type="xsd:string" />
									<xsd:element name="allow-html-in-label" type="xsd:boolean" minOccurs="0" />
									<xsd:element name="page-layout" type="xsd:string" minOccurs="0" />
									<xsd:element name="widgets" type="Widgets" />
									<xsd:element name="page-validators" type="Validators" minOccurs="0" />
									<xsd:element name="next-page" type="xsd:string" minOccurs="0" />
									<xsd:element name="actions" type="Actions" minOccurs="0" />
								</xsd:all>
								<xsd:attribute name="id" type="xsd:string" />
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="confirmation-layout" type="xsd:string" minOccurs="0" />
			<xsd:element name="confirmation-message" type="xsd:string" minOccurs="0" />
			<xsd:element name="redirection-url" type="RedirectionURL" minOccurs="0" />
			<xsd:element name="transient-data" type="TransientData" minOccurs="0" />
			<xsd:element name="connectors" type="Connectors" minOccurs="0"/>
			<xsd:element name="permissions" type="xsd:string" />
			<xsd:element name="next-form" type="xsd:string" minOccurs="0" />
			<xsd:element name="form-type" type="FormType" />
		</xsd:all>
		<xsd:attribute name="id" type="xsd:string" />
		<xsd:attribute name="first-page" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="TransientData">
		<xsd:sequence>
			<xsd:element name="data" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="classname" type="xsd:string" />
						<xsd:element name="value" type="xsd:string" minOccurs="0" />
					</xsd:all>
					<xsd:attribute name="name" type="xsd:string" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Widgets">
		<xsd:sequence>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="widget" type="Widget"/>
				<xsd:element name="group" type="WidgetGroup"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Widget">
		<xsd:all>
			<xsd:element name="variable-bound" type="xsd:string" minOccurs="0" />
			<xsd:element name="title" type="xsd:string" minOccurs="0" />
			<xsd:element name="max-length" type="xsd:integer" minOccurs="0" />
			<xsd:element name="max-height" type="xsd:integer" minOccurs="0" />
			<xsd:element name="style" type="xsd:string" minOccurs="0" />
			<xsd:element name="label" type="xsd:string" minOccurs="0" />
			<xsd:element name="label-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="label-position" type="ItemPosition" minOccurs="0" />
			<xsd:element name="allow-html-in-label" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="allow-html-in-field" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="mandatory" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="readonly" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="initial-value" type="FieldValue" minOccurs="0" />
			<xsd:element name="display-format" type="xsd:string" minOccurs="0" />
			<xsd:element name="items-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="html-attributes" type="HTMLAttributes" minOccurs="0" />
			<xsd:element name="available-values" type="AvailableValues" minOccurs="0" />
			<xsd:element name="validators" type="Validators" minOccurs="0" />
			<xsd:element name="label-button" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="max-items" type="xsd:integer" minOccurs="0" />
			<xsd:element name="multi-instantiated" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="max-instances" type="xsd:string" minOccurs="0" />
			<xsd:element name="min-instances" type="xsd:string" minOccurs="0" />
			<xsd:element name="add-label" type="xsd:string" minOccurs="0" />
			<xsd:element name="add-label-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="add-title" type="xsd:string" minOccurs="0" />
			<xsd:element name="remove-label" type="xsd:string" minOccurs="0" />
			<xsd:element name="remove-label-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="remove-title" type="xsd:string" minOccurs="0" />
			<xsd:element name="display-attachment-image" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="display-condition" type="xsd:string" minOccurs="0" />
			<xsd:element name="image-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="table-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="cell-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="headings-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="headings-positions" type="HeadingsPositions" minOccurs="0" />
			<xsd:element name="horizontal-header" type="xsd:string" minOccurs="0" />
			<xsd:element name="vertical-header" type="xsd:string" minOccurs="0" />
			<xsd:element name="select-mode" type="SelectMode" minOccurs="0" />
			<xsd:element name="selected-items-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="value-column-index" type="xsd:string" minOccurs="0" />
			<xsd:element name="max-rows" type="xsd:string" minOccurs="0" />
			<xsd:element name="min-rows" type="xsd:string" minOccurs="0" />
			<xsd:element name="max-columns" type="xsd:string" minOccurs="0" />
			<xsd:element name="min-columns" type="xsd:string" minOccurs="0" />
			<xsd:element name="variable-columns" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="variable-rows" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="dependencies" type="Dependencies" minOccurs="0" />
			<xsd:element name="display-before-event" type="xsd:string" minOccurs="0" />
			<xsd:element name="display-after-event" type="xsd:string" minOccurs="0" />
			<xsd:element name="value-after-event" type="FieldValue" minOccurs="0" />
			<xsd:element name="available-values-after-event" type="AvailableValues" minOccurs="0" />
			<xsd:element name="widget-position" type="WidgetPosition" minOccurs="0" />
			<xsd:element name="delay_millis" type="xsd:integer" minOccurs="0" />
			<xsd:element name="sub-title" type="SubTitle" minOccurs="0" />
			<xsd:element name="popup-tooltip" type="xsd:string" minOccurs="0" />
		</xsd:all>
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="type" type="WidgetType" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="WidgetPosition">
		<xsd:all>
			<xsd:element name="row" type="xsd:integer" />
			<xsd:element name="column" type="xsd:integer" />
			<xsd:element name="rowspan" type="xsd:integer" minOccurs="0" />
			<xsd:element name="colspan" type="xsd:integer" minOccurs="0" />
			<xsd:element name="cell-styles" type="xsd:string" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>
	
	<xsd:complexType name="WidgetGroup">
		<xsd:all>
			<xsd:element name="variable-bound" type="xsd:string" minOccurs="0" />
			<xsd:element name="title" type="xsd:string" minOccurs="0" />
			<xsd:element name="style" type="xsd:string" minOccurs="0" />
			<xsd:element name="label" type="xsd:string" minOccurs="0" />
			<xsd:element name="label-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="label-position" type="ItemPosition" minOccurs="0" />
			<xsd:element name="allow-html-in-label" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="initial-value" type="FieldValue" minOccurs="0" />
			<xsd:element name="multi-instantiated" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="iterator-name" type="xsd:string" minOccurs="0" />
			<xsd:element name="max-instances" type="xsd:string" minOccurs="0" />
			<xsd:element name="min-instances" type="xsd:string" minOccurs="0" />
			<xsd:element name="add-label" type="xsd:string" minOccurs="0" />
			<xsd:element name="add-label-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="add-title" type="xsd:string" minOccurs="0" />
			<xsd:element name="remove-label" type="xsd:string" minOccurs="0" />
			<xsd:element name="remove-label-style" type="xsd:string" minOccurs="0" />
			<xsd:element name="remove-title" type="xsd:string" minOccurs="0" />
			<xsd:element name="display-condition" type="xsd:string" minOccurs="0" />
			<xsd:element name="dependencies" type="Dependencies" minOccurs="0" />
			<xsd:element name="display-before-event" type="xsd:string" minOccurs="0" />
			<xsd:element name="display-after-event" type="xsd:string" minOccurs="0" />
			<xsd:element name="value-after-event" type="FieldValue" minOccurs="0" />
			<xsd:element name="widgets" type="Widgets" minOccurs="0" />
			<xsd:element name="rows-styles" type="RowsStyles" minOccurs="0" />
			<xsd:element name="columns-styles" type="ColumnsStyles" minOccurs="0" />
			<xsd:element name="widget-position" type="WidgetPosition" minOccurs="0" />
		</xsd:all>
		<xsd:attribute name="id" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="FieldValue">
		<xsd:choice>
			<xsd:element name="expression" type="xsd:string" minOccurs="0" />
			<xsd:element name="connectors" type="Connectors" minOccurs="0" />
		</xsd:choice>
	</xsd:complexType>
	
	<xsd:complexType name="AvailableValues">
		<xsd:choice>
			<xsd:element name="expression" type="xsd:string" minOccurs="0" />
			<xsd:element name="connectors" type="Connectors" minOccurs="0"/>
			<xsd:element name="values-list" type="ValuesList" minOccurs="0" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="Connectors">
		<xsd:sequence>
			<xsd:element name="connector" type="Connector" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Connector">
		<xsd:all>
			<xsd:element name="classname" type="xsd:string" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="throw-exception" type="xsd:boolean" />
			<xsd:element name="input-parameters" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="input-parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="output-parameters" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="output-parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:all>
	</xsd:complexType>
	
	<xsd:complexType name="Parameter">
		<xsd:sequence>
			<xsd:element name="value" type="xsd:string" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="RowsStyles">
		<xsd:sequence>
			<xsd:element name="row-style" minOccurs="0" maxOccurs="unbounded">
		        <xsd:complexType>
		          <xsd:simpleContent>
		            <xsd:extension base="xsd:string">
		              <xsd:attribute name="row" type="xsd:string" />
		            </xsd:extension>
		          </xsd:simpleContent>
		        </xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="ColumnsStyles">
		<xsd:sequence>
			<xsd:element name="column-style" minOccurs="0" maxOccurs="unbounded">
		        <xsd:complexType>
		          <xsd:simpleContent>
		            <xsd:extension base="xsd:string">
		              <xsd:attribute name="column" type="xsd:string" />
		            </xsd:extension>
		          </xsd:simpleContent>
		        </xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="ValuesList">
		<xsd:sequence>
			<xsd:element name="available-value" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="label" type="xsd:string" />
						<xsd:element name="value" type="xsd:string" />
					</xsd:all>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="HTMLAttributes">
		<xsd:sequence>
			<xsd:element name="html-attribute" minOccurs="0" maxOccurs="unbounded">
		        <xsd:complexType>
		          <xsd:simpleContent>
		            <xsd:extension base="xsd:string">
		              <xsd:attribute name="name" type="xsd:string" />
		            </xsd:extension>
		          </xsd:simpleContent>
		        </xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="HeadingsPositions">
		<xsd:all>
			<xsd:element name="left-headings" type="xsd:boolean" />
			<xsd:element name="top-headings" type="xsd:boolean" />
			<xsd:element name="right-headings" type="xsd:boolean" />
			<xsd:element name="bottom-headings" type="xsd:boolean" />
		</xsd:all>
	</xsd:complexType>
	
	<xsd:complexType name="Dependencies">
		<xsd:sequence>
			<xsd:element name="dependency" minOccurs="0" maxOccurs="unbounded">
		        <xsd:complexType>
		        	<xsd:all>
		        		<xsd:element name="depends-on" type="xsd:string" />
		        		<xsd:element name="refresh-on-change" type="xsd:boolean" minOccurs="0" />
					</xsd:all>
		        </xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Validators">
		<xsd:sequence>
			<xsd:element name="validator" minOccurs="0" maxOccurs="unbounded" >
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="classname" type="xsd:string" />
						<xsd:element name="label" type="xsd:string" />
						<xsd:element name="parameter" type="xsd:string" minOccurs="0" />
						<xsd:element name="style" type="xsd:string" minOccurs="0" />
						<xsd:element name="position" type="ValidatorPosition" minOccurs="0" />
					</xsd:all>
					<xsd:attribute name="id" type="xsd:string" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="RedirectionURL">
		<xsd:all>
			<xsd:element name="url" type="xsd:string" minOccurs="0" />
			<xsd:element name="transmit-submission-url" type="xsd:boolean" minOccurs="0" />
			<xsd:element name="actions" type="Actions" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>
	
	<xsd:complexType name="SubTitle">
		<xsd:all>
			<xsd:element name="label" type="xsd:string" />
			<xsd:element name="position" type="SubTitlePosition" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="Actions">
		<xsd:sequence>
			<xsd:element name="action" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="variable" type="xsd:string" minOccurs="0" />
						<xsd:element name="attachment" type="xsd:string" minOccurs="0" />
						<xsd:element name="variable-type" type="xsd:string" minOccurs="0" />
						<xsd:element name="expression" type="xsd:string" minOccurs="0" />
						<xsd:element name="submit-button" type="xsd:string" minOccurs="0" />
						<xsd:element name="connector" type="Connector" minOccurs="0" />
					</xsd:all>
					<xsd:attribute name="type" type="ActionType" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="ActionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SET_VARIABLE"/>
			<xsd:enumeration value="SET_ATTACHMENT"/>
			<xsd:enumeration value="EXECUTE_SCRIPT"/>
			<xsd:enumeration value="EXECUTE_CONNECTOR"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="WidgetType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MESSAGE"/>
			<xsd:enumeration value="TEXT"/>
			<xsd:enumeration value="TEXTAREA"/>
			<xsd:enumeration value="RICH_TEXTAREA"/>
			<xsd:enumeration value="TEXTBOX"/>
			<xsd:enumeration value="RADIOBUTTON_GROUP"/>
			<xsd:enumeration value="LISTBOX_SIMPLE"/>
			<xsd:enumeration value="LISTBOX_MULTIPLE"/>
			<xsd:enumeration value="SUGGESTBOX"/>
			<xsd:enumeration value="SUGGESTBOX_ASYNC"/>
			<xsd:enumeration value="CHECKBOX"/>
			<xsd:enumeration value="CHECKBOX_GROUP"/>
			<xsd:enumeration value="DATE"/>
			<xsd:enumeration value="DURATION"/>
			<xsd:enumeration value="PASSWORD"/>
			<xsd:enumeration value="FILEUPLOAD"/>
			<xsd:enumeration value="FILEDOWNLOAD"/>
			<xsd:enumeration value="IMAGE"/>
			<xsd:enumeration value="TABLE"/>
			<xsd:enumeration value="EDITABLE_GRID"/>
			<xsd:enumeration value="IFRAME"/>
			<xsd:enumeration value="HIDDEN"/>
			<xsd:enumeration value="BUTTON"/>
			<xsd:enumeration value="BUTTON_SUBMIT"/>
			<xsd:enumeration value="BUTTON_NEXT"/>
			<xsd:enumeration value="BUTTON_PREVIOUS"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="ItemPosition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="LEFT"/>
			<xsd:enumeration value="TOP"/>
			<xsd:enumeration value="RIGHT"/>
			<xsd:enumeration value="BOTTOM"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="ValidatorPosition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TOP"/>
			<xsd:enumeration value="BOTTOM"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="SubTitlePosition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TOP"/>
			<xsd:enumeration value="BOTTOM"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="SelectMode">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="NONE" />
			<xsd:enumeration value="SINGLE" />
			<xsd:enumeration value="MULTIPLE" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="FormType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="entry" />
			<xsd:enumeration value="view" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== fivegg/bbonita-console-5-10-1/forms/forms-server/src/test/resources/forms_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<forms-definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="forms.xsd" product-version="5.3">
	<application name="ApprovalWorkflow" version="1.0">
		<application-label>Approval Workflow</application-label>
		<application-template>html/bonita_process_default.html
		</application-template>
		<mandatory-symbol>!</mandatory-symbol>
		<mandatory-label>obligatoire</mandatory-label>
		<mandatory-style>form_mandatory</mandatory-style>
		<error-template>html/bonita_default_error.html</error-template>
		<forms>
			<form id="activity$Request">
				<form-type>entry</form-type>
				<pages>
					<page id="0">
						<page-label>Page 1 label</page-label>
						<page-template>html/request.html</page-template>
						<widgets>
							<widget id="Request_Applications" type="TEXTBOX">
								<max-length>8</max-length>
								<title>Commentaire</title>
								<style>form_input</style>
								<label>Comment</label>
								<label-style>form_label</label-style>
								<mandatory>true</mandatory>
								<validators>
									<validator id="field_validator">
										<class>org.bonitasoft.forms.server.validator.NumericDoubleFieldValidator
										</class>
										<label>wrong field value : this field only tolerates numbers
										</label>
										<style>field_validator</style>
									</validator>
								</validators>
							</widget>
							<widget id="test_widget1" type="FILEUPLOAD">
								<title>File</title>
								<initial-value>
									<expression>attachment</expression>
								</initial-value>
								<style>form_input</style>
								<label>File</label>
								<label-style>form_label</label-style>
								<mandatory>true</mandatory>
							</widget>
							<widget id="test_widget2" type="TEXTAREA">
								<max-length>50</max-length>
								<max-height>2</max-height>
								<initial-value>
									<expression>test content</expression>
								</initial-value>
								<title>Comment text area</title>
								<style>form_input</style>
								<label>Comment text area</label>
								<label-style>form_label</label-style>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test_widget3" type="CHECKBOX">
								<initial-value>
									<expression>true</expression>
								</initial-value>
								<title>Comment checkbox</title>
								<style>form_input</style>
								<label>Comment checkbox</label>
								<label-style>form_label</label-style>
								<mandatory>true</mandatory>
							</widget>
							<widget id="test_widget4" type="RADIOBUTTON_GROUP">
								<initial-value>
									<expression>yes</expression>
								</initial-value>
								<title>Comment radio</title>
								<style>form_input</style>
								<label>Comment radio</label>
								<label-style>form_label</label-style>
								<items-style>form_input</items-style>
								<available-values>
									<values-list>
										<available-value>
											<label>yes</label>
											<value>yes</value>
										</available-value>
										<available-value>
											<label>no</label>
											<value>no</value>
										</available-value>
										<available-value>
											<label>maybe</label>
											<value>maybe</value>
										</available-value>
									</values-list>
								</available-values>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test_widget5" type="LISTBOX_SIMPLE">
								<initial-value>
									<expression>elem1</expression>
								</initial-value>
								<title>Comment listbox</title>
								<style>form_input</style>
								<label>Comment listbox</label>
								<label-style>form_label</label-style>
								<available-values>
									<values-list>
										<available-value>
											<label>element 1</label>
											<value>elem1</value>
										</available-value>
										<available-value>
											<label>element 2</label>
											<value>elem2</value>
										</available-value>
									</values-list>
								</available-values>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test_widget6" type="MESSAGE">
								<initial-value>
									<expression>Information message</expression>
								</initial-value>
								<style>form_input</style>
							</widget>
							<widget id="test_widget7" type="LISTBOX_MULTIPLE">
								<max-height>3</max-height>
								<initial-value>
									<expression>${["elem4", "elem2"]}</expression>
								</initial-value>
								<title>Comment listbox multiple</title>
								<style>form_input</style>
								<label>Comment listbox multiple</label>
								<label-style>form_label</label-style>
								<available-values>
									<values-list>
										<available-value>
											<label>element 1</label>
											<value>elem1</value>
										</available-value>
										<available-value>
											<label>element 2</label>
											<value>elem2</value>
										</available-value>
										<available-value>
											<label>element 3</label>
											<value>elem3</value>
										</available-value>
										<available-value>
											<label>element 4</label>
											<value>elem4</value>
										</available-value>
									</values-list>
								</available-values>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test_widget8" type="DATE">
								<title>Comment date</title>
								<style>form_input</style>
								<label>Comment date</label>
								<label-style>form_label</label-style>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test_widget9" type="TEXT">
								<initial-value>
									<expression>test content text</expression>
								</initial-value>
								<title>Comment text</title>
								<style>form_input</style>
								<label>Comment text</label>
								<label-style>form_label</label-style>
							</widget>
							<widget id="next_widget" type="BUTTON_NEXT">
								<title>Next</title>
								<style>button_input</style>
								<label>Next</label>
							</widget>
						</widgets>
						<page-validators>
							<validator id="page_validator">
								<class>org.bonitasoft.forms.application.server.validator.CustomPageValidator
								</class>
								<label>wrong page values : Comment text area and password fields
									must be filled in</label>
								<style>page_validator</style>
							</validator>
						</page-validators>
						<actions>
							<action type="EXECUTE_SCRIPT">
								<expression></expression>
							</action>
						</actions>
					</page>
					<page id="1">
						<page-label>Page 2 label</page-label>
						<page-template>html/request2.html</page-template>
						<widgets>
							<widget id="test2_widget" type="TEXTBOX">
								<max-length>8</max-length>
								<title>Comment</title>
								<style>form_input</style>
								<label>Comment</label>
								<label-style>form_label</label-style>
								<mandatory>true</mandatory>
								<validators>
									<validator id="field_validator2">
										<class>org.bonitasoft.forms.server.validator.NumericDoubleFieldValidator
										</class>
										<label>wrong field value : this field only tolerates numbers
										</label>
										<style>field_validator</style>
									</validator>
								</validators>
							</widget>
							<widget id="test2_widget1" type="PASSWORD">
								<max-length>10</max-length>
								<title>password</title>
								<style>form_input</style>
								<label>password</label>
								<label-style>form_label</label-style>
								<mandatory>true</mandatory>
							</widget>
							<widget id="test2_widget2" type="TEXTAREA">
								<max-length>50</max-length>
								<max-height>2</max-height>
								<initial-value>
									<expression>test content</expression>
								</initial-value>
								<title>Comment text area</title>
								<style>form_input</style>
								<label>Comment text area</label>
								<label-style>form_label</label-style>
								<mandatory>true</mandatory>
							</widget>
							<widget id="test2_widget3" type="CHECKBOX">
								<title>Comment checkbox 2</title>
								<style>form_input</style>
								<label>Comment checkbox 2</label>
								<label-style>form_label</label-style>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test2_widget4" type="RADIOBUTTON_GROUP">
								<title>Comment radio 2</title>
								<style>form_input</style>
								<label>Comment radio 2</label>
								<label-style>form_label</label-style>
								<items-style>form_input</items-style>
								<available-values>
									<values-list>
										<available-value>
											<label>element 1</label>
											<value>elem1</value>
										</available-value>
										<available-value>
											<label>element 2</label>
											<value>elem2</value>
										</available-value>
										<available-value>
											<label>element 3</label>
											<value>elem3</value>
										</available-value>
									</values-list>
								</available-values>
								<mandatory>false</mandatory>
							</widget>
							<widget id="test2_widget5" type="LISTBOX_SIMPLE">
								<initial-value>
									<expression>Word</expression>
								</initial-value>
								<title>Comment listbox 2</title>
								<style>form_input</style>
								<label>Comment listbox 2</label>
								<label-style>form_label</label-style>
								<available-values>
									<values-list>
										<available-value>
											<label>MS Word</label>
											<value>Word</value>
										</available-value>
										<available-value>
											<label>MS Excel</label>
											<value>Excel</value>
										</available-value>
										<available-value>
											<label>MS Outlook</label>
											<value>MailReader</value>
										</available-value>
										<available-value>
											<label>Firefox</label>
											<value>WebBrowser</value>
										</available-value>
